package envelope

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"filippo.io/age"
)

// TestWriteVectors regenerates the cross-language fixtures the Dart
// pairing_client tests against. It only runs when asked:
//
//	PORTLIGHT_WRITE_VECTORS=1 go test ./internal/envelope -run TestWriteVectors
//
// Commit the result; the fixtures are the contract between the two sides.
func TestWriteVectors(t *testing.T) {
	if os.Getenv("PORTLIGHT_WRITE_VECTORS") == "" {
		t.Skip("set PORTLIGHT_WRITE_VECTORS=1 to regenerate")
	}
	b64 := base64.RawURLEncoding
	std := base64.StdEncoding

	seq := func(start byte, n int) []byte {
		b := make([]byte, n)
		for i := range b {
			b[i] = start + byte(i)
		}
		return b
	}
	secret := seq(0x10, SecretSize)
	sid := seq(0xa0, SessionIDSize)
	cliNonce := seq(0x40, NonceSize)
	phoneNonce := seq(0x70, NonceSize)

	identity, err := age.GenerateX25519Identity()
	if err != nil {
		t.Fatal(err)
	}
	recipient := identity.Recipient().String()
	commitment := Commitment(phoneNonce)

	type sealed struct {
		Name      string `json:"name"`
		Plaintext string `json:"plaintext_b64"`
		Sealed    string `json:"sealed_b64"`
	}
	var files []sealed
	for _, c := range []struct {
		name string
		data []byte
	}{
		{"empty", nil},
		{"small_json", []byte(`{"version":1,"hosts":[]}`)},
		{"one_full_chunk", bytes.Repeat([]byte{'a'}, 64*1024)},
		{"two_chunks", bytes.Repeat([]byte{'b'}, 64*1024+1)},
		{"three_chunks", bytes.Repeat([]byte("portlight"), 20000)},
	} {
		out, err := Seal(c.data, recipient)
		if err != nil {
			t.Fatal(err)
		}
		if back, err := Open(out, identity); err != nil || !bytes.Equal(back, c.data) {
			t.Fatalf("%s does not round-trip: %v", c.name, err)
		}
		files = append(files, sealed{c.name, std.EncodeToString(c.data), std.EncodeToString(out)})
	}

	other, _ := age.GenerateX25519Identity()

	relayBoxes := map[string]string{}
	for _, name := range RelayBoxNames {
		relayBoxes[name] = b64.EncodeToString(RelayBox(secret, sid, name))
	}

	vectors := map[string]any{
		"comment": "Generated by cli/internal/envelope/vectors_test.go. " +
			"Byte fields are base64url without padding unless the key ends in _b64 (standard base64). " +
			"Protocol: docs/pairing-protocol.md.",
		"protocol": map[string]any{
			"secret":      b64.EncodeToString(secret),
			"sid":         b64.EncodeToString(sid),
			"cli_nonce":   b64.EncodeToString(cliNonce),
			"phone_nonce": b64.EncodeToString(phoneNonce),
			"recipient":   recipient,
			"commitment":  b64.EncodeToString(commitment),
			"claim_mac":   b64.EncodeToString(ClaimMAC(secret, sid, recipient, commitment)),
			"sas":         SAS(secret, sid, recipient, cliNonce, phoneNonce),
			"reject_mac":  b64.EncodeToString(RejectMAC(secret, sid)),
			"relay_boxes": relayBoxes,
		},
		"age": map[string]any{
			"identity":       identity.String(),
			"recipient":      recipient,
			"other_identity": other.String(),
			"files":          files,
		},
	}
	data, err := json.MarshalIndent(vectors, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join("..", "..", "..", "packages", "pairing_client", "test", "fixtures", "vectors.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, append(data, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s", path)
}
